# Generated by Django 3.2.25 on 2025-03-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Список товаров', 'verbose_name_plural': 'Список товаров'},
        ),
    ]
